# Generated by Django 4.0.4 on 2022-06-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='img1',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='img2',
            field=models.ImageField(default='one', upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='par',
            field=models.TextField(default='Add Something'),
            preserve_default=False,
        ),
    ]
